#!/bin/sh
python /home/dotcloud/code/setupAndBase/setupApp.py /home/dotcloud/code/config/crowded.cfg dotcloud >> /home/dotcloud/code/errors/setupAppErrors.log 2>&1

crontab /home/dotcloud/code/config/_crontab

