#!/bin/sh
mkdir /home/dotcloud/code/logs
chmod 777 /home/dotcloud/code/logs

python /home/dotcloud/code/setupAndBase/setupApp.py /home/dotcloud/code/config/crowded.cfg dotcloud

crontab /home/dotcloud/code/config/_crontab

